try, without success, to reproduce the ImportError: cannot import name 'io' found loading wc_lang_33075c4/wc_lang/util.py in tricky_package; it's probably caused deep in wc_lang_33075c4/wc_lang/core.py